version: "3.9"
services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mqtt-broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    restart: unless-stopped

  backend:
    build:
      context: ../apps/backend
      dockerfile: Dockerfile
    container_name: ambulance-backend
    environment:
      - PORT=8080
      - MQTT_BROKER_URL=mqtt://mosquitto:1883
      - FRONTEND_ORIGIN=*
      - GOOGLE_MAPS_API_KEY=
    depends_on:
      - mosquitto
    ports:
      - "8080:8080"
    restart: unless-stopped